{% set version = "0.4.0" %}

package:
  name: nilearn
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  sha256: bb692254bde35d7e1d3d1534d9b3117810b35a744724625f150fbbc64d519c02

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - scikit-learn
    - nibabel
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - matplotlib

test:
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD 3-clause
  license_file: LICENSE
  summary: 'Statistical learning for neuroimaging in Python'

extra:
  recipe-maintainers:
    - lesteve
    - ocefpaf
    - GaelVaroquaux
    - KamalakerDadi
