{% set version = "0.2.4" %}

package:
  name: nilearn
  version: {{ version }}

source:
  fn: nilearn-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/n/nilearn/nilearn-{{ version }}.tar.gz
  md5: 66145792fb2aebf51e221225bd210534

build:
    number: 1
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - numpy
    - scipy
    - scikit-learn
    - nibabel
  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - nibabel
    - matplotlib

test:
  imports:
    - nilearn

about:
  home: https://nilearn.github.io
  license: BSD 3-clause
  summary: Statistical learning for neuroimaging in Python

extra:
  recipe-maintainers:
    - lesteve
