travis:
  secure:
    BINSTAR_TOKEN: vBeDQzWXflVYWFF5/Fx1ffVvG187iwaQ+edV22w4ZNAIiEIZhCoJIGcwwB62hldoNwOT6j6obdhR7Wmb+PjyhNYxqYhe++Djk5cxbsYUMR1ZUFcdHDvAiuKErY4zPbNWWZD6vpTuySaK+8ye3CeqhItjMU052YhpJWXAtbcImD97t/B5ttLeYwPLJGyof/6mJyaybROhatpBA0UZHIZa75YD4W60Y48ejCIVvZ8rNoRnUGjvFxfnVJmaemRSnlcSPypOgCoenOofBpxL5USyz1wzLy5kyVjWGl7pyQcCRGptOe3DXZJtijyvmk+p0T/eqzL2cqRJRB85m+WyYlHdRu2h2YJfxf9khKXNLEF9gumPkz/1G8hvk/Nr80E4zn23y7f3x9SRwSKZm3h8DzTNIqI3zRv7F2//gTDucJRPnA9elYszSJ2oqgLNtnX8O2dek00vpQ7NOWLbYyZpkDorr/654v97VYwMbtQ4jfNnmUNta+VbIao68xCXJ3ajiicdy4XmlrRCeEajycLSqRmk+Q1NmWobN1ZJEWutk5G/LctR7Y8WP7/mqWrLdbsnUp1zIzXh6iRL3dKYmQzK/u0OumXFDk9BWpnsvjFLQ4+goa57yuqBQI5IRRo064n8I92AFRkFVhEuXJVTc1RrDNqBYh5eMaEfWDNmuLf7j+qYS24=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
