travis:
  secure:
    BINSTAR_TOKEN: e8DtyjcMlaQsI2otSJaIV/i0gH3Ma7u0qkToXw7ebY1jyNmcob8VOWK66MLKTnRNJTmpkqlgkBGJdnStgBRU2LuvB1Rd5agKfGNHYBtjlHgVUC6PFXtHyibRxVrBBYEBY0xuP4ki4ZPRTyR4WRRWY9R43Vr/LxFjr6AzAefuSrMlOaQeFZ7QNaF4GA6r4vAWc/3ZHsBPF8HTrDsnNz3jU0z7+fZ4bmXHgCnPZ627KZeiGpNc0dD+OT78rcVrE/4yXHZfVGzLefDQ0ddmgnd/RaU5iB1SIW6P+EUSCB0biCGtpoCdB7RJEsGvA+K4bM2RgK7LIXPoFwyCtrFPsUIy4H7qJDB46UATsETRsqeErfwA6NCqkJIdKxgBzuLZqUpmNuqn/6Y9yGkrxoh6TsId26lPDhZx4y87x9OORwGTv54WvBZ7nKxbRB+uzrwt/ZxP8279SW6HFzpRFaoJxurVhZ9jgttYyvl+aVecI+uGh7BmMBCC+uG9c17wc0LsU5WzEK8IeGBCNsMcysubVnCvUM3VTUNlLRSY7fkKQtkPYUnQxMghd4IefSszQp9nFMs833ERtSYkDRI1hPieClqUSVVzp2CQITKnlgjkY8y0ShxuduwavSDhmB7e88Z574gbMYLtnHwc2tgwpabfL0KHyfFzTZiflsWXW6gU+0h4mPs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
